import localFont from "next/font/local";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import 'react-toastify/dist/ReactToastify.css';
import Header from './Components/Header/page'
import Footer from './Components/Footer/page'
import Slidebar from './Components/Slidebar/page'


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Crud Operation",
  description: "Generated by Saurav",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        <div style={{display:'flex' , maxHeight:'86vh', overflow:'hidden'}}>
        <Slidebar/>
        {children}
        </div>
        <Footer/>
      </body>
    </html>
  );
}
